In [2]:
%pip install psycopg2-binary

import psycopg2 #import the PostgreSQL adapter
import pandas as pd #Used for data analysis and manipilation
from sqlalchemy import create_engine #function to vreat a database engine
import numpy as np #For array manipulation
from psycopg2 import OperationalError
import re #python string library

Requirement already satisfied: psycopg2-binary in c:\users\marku\anaconda3\lib\site-packages (2.9.10)
Note: you may need to restart the kernel to use updated packages.

In [2]:
db_name = "Traffic 1"  #database parameters
db_user = "postgres"
db_password = "postgres"  
db_host = "localhost"  
db_port = "5432"
db_server = "dw_2025"

def create_connection(db_name, db_user, db_password, db_host, db_port): #Python function to create a connection to PostgreSQL server. (Reused from Data Warehousing Lab3)
    connection = None
    try:
        connection = psycopg2.connect(
            database=db_name,
            user=db_user,
            password=db_password,
            host=db_host,
            port=db_port,
        )
        print("Connection to PostgreSQL DB successful")
    except OperationalError as e:
        print(f"The error '{e}' occurred")
    return connection

connection = create_connection(db_name, db_user, db_password, db_host, db_port)  #Create connection to the PostgreSQL server function

cursor = connection.cursor() #Cursor allow python code to execute PostgreSQL command in a database session

connection_string = f"postgresql+psycopg2://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}" #connection string to the database
engine = create_engine(connection_string) #Create engine for the database

Connection to PostgreSQL DB successful

In [11]:
fatal_df = pd.read_excel(r".\bitre_fatal_crashes_dec2024.xlsx", sheet_name="BITRE_Fatal_Crash", header=None, skiprows=4)
fatal_df.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,Crash ID,State,Month,Year,Dayweek,Time,Crash Type,Number Fatalities,Bus \nInvolvement,Heavy Rigid Truck Involvement,Articulated Truck Involvement,Speed Limit,National Remoteness Areas,SA4 Name 2021,National LGA Name 2021,National Road Type,Christmas Period,Easter Period,Day of week,Time of Day
1,20241115,NSW,12,2024,Friday,04:00:00,Single,1,No,No,No,100,Inner Regional Australia,Riverina,Wagga Wagga,Arterial Road,Yes,No,Weekday,Night
2,20241125,NSW,12,2024,Friday,06:15:00,Single,1,No,No,No,80,Inner Regional Australia,Sydney - Baulkham Hills and Hawkesbury,Hawkesbury,Local Road,No,No,Weekday,Day
3,20246013,Tas,12,2024,Friday,09:43:00,Multiple,1,No,No,No,50,Inner Regional Australia,Launceston and North East,Northern Midlands,Local Road,Yes,No,Weekday,Day
4,20241002,NSW,12,2024,Friday,10:35:00,Multiple,1,No,No,No,100,Outer Regional Australia,New England and North West,Armidale Regional,National or State Highway,No,No,Weekday,Day

In [10]:
dwellings_df = pd.read_csv(r".\LGA (count of dwellings).csv", delimiter='\t', skiprows=5, names=["LGA", "Dwellings"])
dwellings_df.head(10)

                                    LGA  Dwellings
0                              Filters:        NaN
1  Default Summation,"Dwelling Records"        NaN
2                             LGA (EN),        NaN
3                         Albury,25430,        NaN
4              Armidale Regional,12955,        NaN
5                        Ballina,20889,        NaN
6                       Balranald,1091,        NaN
7              Bathurst Regional,18458,        NaN
8                  Bayside (NSW),74840,        NaN
9                    Bega Valley,18867,        NaN

In [13]:
fatal_df = pd.read_excel(r".\bitre_fatalities_dec2024.xlsx", sheet_name="BITRE_Fatality", header=None, skiprows=4)
fatal_df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Crash ID,State,Month,Year,Dayweek,Time,Crash Type,Bus Involvement,Heavy Rigid Truck Involvement,Articulated Truck Involvement,...,Age,National Remoteness Areas,SA4 Name 2021,National LGA Name 2021,National Road Type,Christmas Period,Easter Period,Age Group,Day of week,Time of day
1,20241115,NSW,12,2024,Friday,04:00:00,Single,No,No,No,...,74,Inner Regional Australia,Riverina,Wagga Wagga,Arterial Road,Yes,No,65_to_74,Weekday,Night
2,20241125,NSW,12,2024,Friday,06:15:00,Single,No,No,No,...,19,Inner Regional Australia,Sydney - Baulkham Hills and Hawkesbury,Hawkesbury,Local Road,No,No,17_to_25,Weekday,Day
3,20246013,Tas,12,2024,Friday,09:43:00,Multiple,No,No,No,...,33,Inner Regional Australia,Launceston and North East,Northern Midlands,Local Road,Yes,No,26_to_39,Weekday,Day
4,20241002,NSW,12,2024,Friday,10:35:00,Multiple,No,No,No,...,32,Outer Regional Australia,New England and North West,Armidale Regional,National or State Highway,No,No,26_to_39,Weekday,Day